export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const GET_PROFILE = 'GET_PROFILE';
export const PROFILE_LOADING = 'PROFILE_LOADING';
export const PROFILE_NOT_FOUND = 'PROFILE_NOT_FOUND';
export const CLEAR_CURRENT_PROFILE = 'CLEAR_CURRENT_PROFILE';
export const GET_PROFILES = 'GET_PROFILES';

export const SET_CURRENT_GROUP = 'SET_CURRENT_GROUP';
export const CREATE_GROUP = 'CREATE_GROUP';
export const GET_GROUP = 'GET_GROUP';
export const GROUP_LOADING = 'GROUP_LOADING';
export const GROUP_NOT_FOUND = 'GROUP_NOT_FOUND';
export const CLEAR_CURRENT_GROUP = 'CLEAR_CURRENT_GROUP';